# Generated by Django 3.1.1 on 2022-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_author', models.CharField(max_length=122)),
                ('quote_body', models.TextField()),
                ('context', models.CharField(max_length=122)),
                ('source', models.CharField(max_length=122)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
